'use client';

import React, { useState, useEffect, useCallback } from 'react';
import {
  LOTTERY_CONFIGS,
  generateBolaoOtimizado,
} from '../../lib/lottery-math';
import { fetchWithCsrf } from '@/lib/fetch';
import { getSimpleBetPrice } from '@/lib/lottery-prices';
import type { SavedGame } from '../types';

interface Bolao {
  id: string;
  lottery: string;
  title: string;
  games: string[][];
  total_cost: number;
  cotas_total: number;
  cotas_taken: number;
  taxa_pct: number;
  status: string;
  contest_num: number | null;
  prize_won: number;
  prize_distributed: number;
  share_code: string;
  creator_name: string;
  created_at: string;
  cota_num?: number;
  paid?: number;
  amount_received?: number;
}

interface Props {
  savedGames: SavedGame[];
  activeLottery: string;
  isPro: boolean;
  user: { id: string; name: string; role?: string } | null;
  onUpgrade: () => void;
  playSound: (type: 'click' | 'success' | 'delete') => void;
}

export default function BolaoPanel({
  savedGames,
  activeLottery,
  isPro,
  user,
  onUpgrade,
  playSound,
}: Props) {
  const [subView, setSubView] = useState<'create' | 'my' | 'join'>('create');
  const [selectedGames, setSelectedGames] = useState<string[]>([]);
  const [bolaoTitle, setBolaoTitle] = useState('');
  const [cotasTotal, setCotasTotal] = useState('5');
  const [taxaPct, setTaxaPct] = useState('0');
  const [createdBolao, setCreatedBolao] = useState<{
    id: string;
    shareCode: string;
  } | null>(null);
  const [myBoloes, setMyBoloes] = useState<Bolao[]>([]);
  const [joinedBoloes, setJoinedBoloes] = useState<Bolao[]>([]);
  const [joinCode, setJoinCode] = useState('');
  const [loading, setLoading] = useState(false);
  const [feedback, setFeedback] = useState('');
  // Auto-generate state
  const [autoGameCount, setAutoGameCount] = useState(5);
  const [autoGenerated, setAutoGenerated] = useState<
    { numbers: string; id: string }[]
  >([]);

  const config = LOTTERY_CONFIGS[activeLottery as keyof typeof LOTTERY_CONFIGS];

  const handleAutoGenerate = () => {
    playSound('click');
    if (!config) return;
    const games = generateBolaoOtimizado(config, autoGameCount);
    const newGames = games.map((g, i) => ({
      numbers: g.numbers.map((n) => String(n).padStart(2, '0')).join(', '),
      id: `auto-${Date.now()}-${i}`,
    }));
    setAutoGenerated(newGames);
  };

  const handleSaveAutoGames = async () => {
    if (!user || autoGenerated.length === 0) return;
    for (const g of autoGenerated) {
      try {
        await fetchWithCsrf('/api/bets', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            lottery: activeLottery,
            contest_num: 0,
            numbers: g.numbers,
            cost: getSimpleBetPrice(activeLottery),
            prize_won: 0,
            hits: 0,
          }),
        });
      } catch {
        /* ignore */
      }
    }
    playSound('success');
    setAutoGenerated([]);
  };

  const fetchMyBoloes = useCallback(async () => {
    try {
      const res = await fetchWithCsrf('/api/bolao');
      if (res.ok) {
        const data = await res.json();
        setMyBoloes(data.created || []);
        setJoinedBoloes(data.joined || []);
      }
    } catch {
      /* ignore */
    }
  }, []);

  useEffect(() => {
    let cancelled = false;

    queueMicrotask(async () => {
      try {
        const res = await fetchWithCsrf('/api/bolao');
        if (!res.ok || cancelled) {
          return;
        }
        const data = await res.json();
        if (cancelled) {
          return;
        }
        setMyBoloes(data.created || []);
        setJoinedBoloes(data.joined || []);
      } catch {
        /* ignore */
      }
    });

    return () => {
      cancelled = true;
    };
  }, []);

  const handleCreate = async () => {
    if (selectedGames.length === 0 || !bolaoTitle.trim()) {
      setFeedback('⚠️ Preencha o título e selecione pelo menos 1 jogo.');
      return;
    }

    setLoading(true);
    setFeedback('');

    try {
      const gamesArrays = selectedGames.map((id) => {
        const g = savedGames.find((s) => s.id === id);
        return g ? g.numbers.split(/[,;\s]+/).filter(Boolean) : [];
      });

      const res = await fetchWithCsrf('/api/bolao', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          lottery: activeLottery,
          title: bolaoTitle.trim(),
          games: gamesArrays,
          cotas_total: parseInt(cotasTotal) || 5,
          taxa_pct: isPro ? parseFloat(taxaPct) || 0 : 0,
        }),
      });

      if (res.ok) {
        const data = await res.json();
        setCreatedBolao({ id: data.id, shareCode: data.shareCode });
        setFeedback('✓ Bolão criado com sucesso!');
        playSound('success');
        void fetchMyBoloes();
      } else {
        const err = await res.json();
        setFeedback(`⚠️ ${err.error || 'Erro ao criar'}`);
      }
    } catch {
      setFeedback('⚠️ Erro de conexão');
    }
    setLoading(false);
  };

  const handleJoin = async () => {
    if (!joinCode.trim()) {
      setFeedback('⚠️ Digite um código de bolão.');
      return;
    }
    setLoading(true);
    try {
      const res = await fetchWithCsrf('/api/bolao/join', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ shareCode: joinCode.trim() }),
      });

      if (res.ok) {
        const data = await res.json();
        setFeedback(
          `✓ Você entrou! Cota #${data.cota} — R$ ${data.amount_due.toFixed(2).replace('.', ',')}`
        );
        playSound('success');
        setJoinCode('');
        void fetchMyBoloes();
      } else {
        const err = await res.json();
        setFeedback(`⚠️ ${err.error}`);
      }
    } catch {
      setFeedback('⚠️ Erro de conexão');
    }
    setLoading(false);
  };

  const handleDelete = async (id: string) => {
    try {
      const res = await fetchWithCsrf(`/api/bolao?id=${id}`, {
        method: 'DELETE',
      });
      if (res.ok) {
        setMyBoloes((prev) => prev.filter((b) => b.id !== id));
        playSound('delete');
      }
    } catch {
      /* ignore */
    }
  };

  const generateBolaoMessage = (bolao: Bolao): string => {
    const config =
      LOTTERY_CONFIGS[bolao.lottery as keyof typeof LOTTERY_CONFIGS];
    const gamePrice = getSimpleBetPrice(bolao.lottery);
    const totalCost = gamePrice * bolao.games.length;
    const cotaValue = totalCost / bolao.cotas_total;

    let msg = `🍀 *BOLÃO ${config?.name || bolao.lottery.toUpperCase()}* 🍀\n`;
    msg += `📋 *${bolao.title}*\n\n`;

    bolao.games.forEach((game, i) => {
      const nums = game
        .map((n: string) => String(n).padStart(2, '0'))
        .join(' - ');
      msg += `🎰 *Jogo ${i + 1}:* ${nums}\n`;
    });

    msg += `\n💰 *Custo total:* R$ ${totalCost.toFixed(2).replace('.', ',')}\n`;
    msg += `👥 *Cotas:* ${bolao.cotas_total} (${bolao.cotas_taken} preenchidas)\n`;
    msg += `💵 *Valor por cota:* R$ ${cotaValue.toFixed(2).replace('.', ',')}\n`;

    if (bolao.taxa_pct > 0) {
      msg += `⚙️ *Taxa organização:* ${bolao.taxa_pct}%\n`;
    }

    if (bolao.share_code) {
      msg += `\n🔗 *Entre pelo link:*\nwww.meutrevo.com/bolao?c=${bolao.share_code}\n`;
    }

    msg += `\n🤖 Montado no Meu Trevo — IA + Estatística`;
    return msg;
  };

  const handleCopyMessage = (bolao: Bolao) => {
    const msg = generateBolaoMessage(bolao);
    navigator.clipboard.writeText(msg);
    setFeedback('✓ Mensagem copiada!');
    setTimeout(() => setFeedback(''), 2000);
  };

  const handleShareWhatsApp = (bolao: Bolao) => {
    const msg = generateBolaoMessage(bolao);
    window.open(`https://wa.me/?text=${encodeURIComponent(msg)}`, '_blank');
  };

  const filteredGames = savedGames.filter((g) => g.lottery === activeLottery);

  return (
    <div
      className="glass-panel animate-fade-in"
      style={{
        display: 'flex',
        flexDirection: 'column',
        gap: '1rem',
        padding: '1.25rem',
      }}
    >
      {/* Header */}
      <div
        style={{
          borderBottom: '1px solid rgba(255,255,255,0.05)',
          paddingBottom: '0.75rem',
        }}
      >
        <h3
          style={{
            fontFamily: 'var(--font-body)',
            fontSize: '1.1rem',
            fontWeight: 800,
            color: 'white',
            display: 'flex',
            alignItems: 'center',
            gap: '0.5rem',
            margin: 0,
          }}
        >
          <span>🎲</span> BOLÃO INTELIGENTE
        </h3>
        <p
          style={{
            fontSize: '0.75rem',
            color: 'var(--text-muted)',
            marginTop: '0.25rem',
          }}
        >
          Crie, gerencie e compartilhe bolões com seus amigos.
        </p>
      </div>

      {/* Explanation */}
      <div
        style={{
          fontSize: '0.65rem',
          color: 'var(--text-muted)',
          lineHeight: 1.6,
          padding: '0.6rem',
          borderRadius: '8px',
          background: 'rgba(0,240,255,0.03)',
          border: '1px solid rgba(0,240,255,0.08)',
        }}
      >
        <strong style={{ color: 'white' }}>Como funciona o Bolão:</strong>
        <br />
        Um bolão é um grupo de pessoas que apostam <em>juntos</em>. Vocês
        dividem o custo dos jogos e, se ganharem, dividem o prêmio
        proporcionalmente.
        <br />
        <br />
        <strong style={{ color: '#00e676' }}>1.</strong> Gere ou selecione jogos
        → <strong style={{ color: '#ffd600' }}>2.</strong> Defina quantas cotas
        (pessoas) → <strong style={{ color: 'var(--accent-color)' }}>3.</strong>{' '}
        Compartilhe o código
        <br />
        <br />
        <strong style={{ color: 'white' }}>Dica:</strong> Quanto mais jogos no
        bolão, maiores as chances. O sistema gera jogos com{' '}
        <em>números dispersos</em> para maximizar a cobertura.
      </div>

      {/* Sub-nav */}
      <div style={{ display: 'flex', gap: '0.5rem' }}>
        {(
          [
            ['create', 'Criar'],
            ['my', `Meus (${myBoloes.length})`],
            ['join', 'Entrar'],
          ] as const
        ).map(([key, label]) => (
          <button
            key={key}
            onClick={() => {
              setSubView(key);
              setFeedback('');
              setCreatedBolao(null);
            }}
            style={{
              flex: 1,
              padding: '0.5rem',
              borderRadius: '8px',
              border: '1px solid',
              borderColor:
                subView === key
                  ? config?.color || '#00ff88'
                  : 'rgba(255,255,255,0.1)',
              background:
                subView === key
                  ? `${config?.color || '#00ff88'}15`
                  : 'transparent',
              color: subView === key ? 'white' : 'var(--text-muted)',
              fontSize: '0.75rem',
              fontWeight: 600,
              cursor: 'pointer',
            }}
          >
            {label}
          </button>
        ))}
      </div>

      {feedback && (
        <div
          style={{
            padding: '0.5rem 0.75rem',
            borderRadius: '8px',
            fontSize: '0.75rem',
            background: feedback.startsWith('✓')
              ? 'rgba(0,230,118,0.08)'
              : feedback.startsWith('⚠')
                ? 'rgba(255,214,0,0.08)'
                : 'rgba(0,240,255,0.08)',
            border: `1px solid ${feedback.startsWith('✓') ? 'rgba(0,230,118,0.2)' : feedback.startsWith('⚠') ? 'rgba(255,214,0,0.2)' : 'rgba(0,240,255,0.2)'}`,
            color: feedback.startsWith('✓')
              ? '#00e676'
              : feedback.startsWith('⚠')
                ? '#ffd600'
                : 'var(--accent-color)',
          }}
        >
          {feedback}
        </div>
      )}

      {/* CREATE VIEW */}
      {subView === 'create' && (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
          {/* Title */}
          <div>
            <label
              style={{
                fontSize: '0.7rem',
                color: 'var(--text-muted)',
                marginBottom: '0.25rem',
                display: 'block',
              }}
            >
              Nome do Bolão
            </label>
            <input
              type="text"
              value={bolaoTitle}
              onChange={(e) => setBolaoTitle(e.target.value)}
              placeholder="Ex: Bolão do Churrasco 2026"
              maxLength={60}
              style={{
                width: '100%',
                background: 'rgba(0,0,0,0.3)',
                border: '1px solid rgba(255,255,255,0.1)',
                borderRadius: '8px',
                padding: '0.6rem',
                color: 'white',
                fontSize: '0.85rem',
                outline: 'none',
              }}
            />
          </div>

          {/* Auto-generate games */}
          <div
            style={{
              padding: '0.6rem',
              borderRadius: '8px',
              background: 'rgba(0,240,255,0.03)',
              border: '1px solid rgba(0,240,255,0.08)',
            }}
          >
            <div
              style={{
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
                marginBottom: '0.4rem',
              }}
            >
              <label
                style={{
                  fontSize: '0.7rem',
                  color: 'var(--text-muted)',
                  fontWeight: 600,
                }}
              >
                Gerar Jogos automaticamente
              </label>
              <div
                style={{ display: 'flex', alignItems: 'center', gap: '0.3rem' }}
              >
                <input
                  type="number"
                  min={1}
                  max={50}
                  value={autoGameCount}
                  onChange={(e) =>
                    setAutoGameCount(parseInt(e.target.value) || 5)
                  }
                  style={{
                    width: '45px',
                    background: 'rgba(0,0,0,0.3)',
                    border: '1px solid rgba(255,255,255,0.1)',
                    borderRadius: '4px',
                    padding: '0.2rem 0.3rem',
                    color: 'white',
                    fontSize: '0.7rem',
                    textAlign: 'center',
                    outline: 'none',
                  }}
                />
                <span
                  style={{ fontSize: '0.6rem', color: 'var(--text-muted)' }}
                >
                  jogos
                </span>
              </div>
            </div>
            <p
              style={{
                fontSize: '0.55rem',
                color: 'var(--text-muted)',
                marginBottom: '0.4rem',
                lineHeight: 1.4,
              }}
            >
              O sistema gera jogos com números dispersos para maximizar a
              cobertura do bolão.
            </p>
            <button
              onClick={handleAutoGenerate}
              style={{
                width: '100%',
                padding: '0.45rem',
                borderRadius: '6px',
                border: `1px solid ${config?.color || '#00ff88'}`,
                background: `${config?.color || '#00ff88'}15`,
                color: config?.color || '#00ff88',
                fontSize: '0.7rem',
                fontWeight: 600,
                cursor: 'pointer',
              }}
            >
              🎲 Gerar {autoGameCount} Jogos Otimizados
            </button>
            {autoGenerated.length > 0 && (
              <div style={{ marginTop: '0.5rem' }}>
                <div
                  style={{
                    display: 'flex',
                    justifyContent: 'space-between',
                    alignItems: 'center',
                    marginBottom: '0.3rem',
                  }}
                >
                  <span
                    style={{
                      fontSize: '0.6rem',
                      color: config?.color || '#00ff88',
                      fontWeight: 600,
                    }}
                  >
                    {autoGenerated.length} jogos gerados
                  </span>
                  <button
                    onClick={handleSaveAutoGames}
                    style={{
                      background: 'none',
                      border: 'none',
                      color: '#00e676',
                      fontSize: '0.6rem',
                      cursor: 'pointer',
                      textDecoration: 'underline',
                    }}
                  >
                    Salvar todos e usar
                  </button>
                </div>
                <div
                  style={{
                    display: 'flex',
                    flexDirection: 'column',
                    gap: '0.2rem',
                    maxHeight: '120px',
                    overflowY: 'auto',
                  }}
                >
                  {autoGenerated.map((g) => (
                    <div
                      key={g.id}
                      style={{
                        display: 'flex',
                        gap: '0.15rem',
                        flexWrap: 'wrap',
                      }}
                    >
                      {g.numbers
                        .split(', ')
                        .slice(0, 8)
                        .map((n, i) => (
                          <span
                            key={i}
                            style={{
                              width: '20px',
                              height: '20px',
                              borderRadius: '50%',
                              fontSize: '0.55rem',
                              fontWeight: 700,
                              background: `${config?.color || '#00ff88'}22`,
                              border: `1px solid ${config?.color || '#00ff88'}`,
                              color: 'white',
                              display: 'flex',
                              alignItems: 'center',
                              justifyContent: 'center',
                            }}
                          >
                            {n}
                          </span>
                        ))}
                      {g.numbers.split(', ').length > 8 && (
                        <span
                          style={{
                            fontSize: '0.55rem',
                            color: 'var(--text-muted)',
                            alignSelf: 'center',
                          }}
                        >
                          +{g.numbers.split(', ').length - 8}
                        </span>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>

          {/* Select saved games */}
          <div>
            <div
              style={{
                display: 'flex',
                justifyContent: 'space-between',
                marginBottom: '0.35rem',
              }}
            >
              <label style={{ fontSize: '0.7rem', color: 'var(--text-muted)' }}>
                Ou selecione jogos salvos
              </label>
              <button
                onClick={() => {
                  setSelectedGames(
                    selectedGames.length === filteredGames.length
                      ? []
                      : filteredGames.map((g) => g.id)
                  );
                }}
                style={{
                  background: 'none',
                  border: 'none',
                  color: config?.color || 'var(--accent-color)',
                  fontSize: '0.65rem',
                  cursor: 'pointer',
                  textDecoration: 'underline',
                }}
              >
                {selectedGames.length === filteredGames.length
                  ? 'Desmarcar Todas'
                  : 'Selecionar Todas'}
              </button>
            </div>
            {filteredGames.length === 0 ? (
              <p
                style={{
                  fontSize: '0.7rem',
                  color: 'var(--text-muted)',
                  textAlign: 'center',
                  padding: '0.75rem',
                }}
              >
                Nenhum jogo salvo para {config?.name || activeLottery}.
              </p>
            ) : (
              <div
                style={{
                  display: 'flex',
                  flexDirection: 'column',
                  gap: '0.3rem',
                  maxHeight: '150px',
                  overflowY: 'auto',
                }}
              >
                {filteredGames.map((game) => (
                  <label
                    key={game.id}
                    style={{
                      display: 'flex',
                      alignItems: 'center',
                      gap: '0.5rem',
                      padding: '0.4rem 0.5rem',
                      background: selectedGames.includes(game.id)
                        ? `${config?.color || '#00ff88'}10`
                        : 'rgba(255,255,255,0.02)',
                      border: `1px solid ${selectedGames.includes(game.id) ? `${config?.color || '#00ff88'}30` : 'rgba(255,255,255,0.05)'}`,
                      borderRadius: '6px',
                      cursor: 'pointer',
                      transition: 'all 0.15s',
                    }}
                  >
                    <input
                      type="checkbox"
                      checked={selectedGames.includes(game.id)}
                      onChange={() => {
                        setSelectedGames((prev) =>
                          prev.includes(game.id)
                            ? prev.filter((id) => id !== game.id)
                            : [...prev, game.id]
                        );
                      }}
                      style={{ accentColor: config?.color || '#00ff88' }}
                    />
                    <div
                      style={{
                        display: 'flex',
                        gap: '0.15rem',
                        flexWrap: 'wrap',
                        flex: 1,
                      }}
                    >
                      {game.numbers
                        .split(/[,;\s]+/)
                        .filter(Boolean)
                        .slice(0, 8)
                        .map((n, i) => (
                          <span
                            key={i}
                            style={{
                              width: '20px',
                              height: '20px',
                              borderRadius: '50%',
                              fontSize: '0.55rem',
                              fontWeight: 700,
                              background: `${config?.color || '#00ff88'}22`,
                              border: `1px solid ${config?.color || '#00ff88'}`,
                              color: 'white',
                              display: 'flex',
                              alignItems: 'center',
                              justifyContent: 'center',
                            }}
                          >
                            {String(n).padStart(2, '0')}
                          </span>
                        ))}
                    </div>
                  </label>
                ))}
              </div>
            )}
          </div>

          {/* Config */}
          <div
            style={{
              display: 'grid',
              gridTemplateColumns: '1fr 1fr',
              gap: '0.5rem',
            }}
          >
            <div>
              <label
                style={{
                  fontSize: '0.65rem',
                  color: 'var(--text-muted)',
                  marginBottom: '0.2rem',
                  display: 'block',
                }}
              >
                Total de Cotas
              </label>
              <input
                type="number"
                min={1}
                max={100}
                value={cotasTotal}
                onChange={(e) => setCotasTotal(e.target.value)}
                style={{
                  width: '100%',
                  background: 'rgba(0,0,0,0.3)',
                  border: '1px solid rgba(255,255,255,0.1)',
                  borderRadius: '8px',
                  padding: '0.5rem',
                  color: 'white',
                  fontSize: '0.85rem',
                  outline: 'none',
                }}
              />
            </div>
            <div>
              <label
                style={{
                  fontSize: '0.65rem',
                  color: 'var(--text-muted)',
                  marginBottom: '0.2rem',
                  display: 'block',
                }}
              >
                Taxa Organizador (%)
                {!isPro && (
                  <span
                    style={{
                      color: '#ffd600',
                      marginLeft: '0.25rem',
                      fontSize: '0.6rem',
                    }}
                  >
                    PRO
                  </span>
                )}
              </label>
              <input
                type="number"
                min={0}
                max={100}
                value={taxaPct}
                onChange={(e) =>
                  isPro ? setTaxaPct(e.target.value) : onUpgrade()
                }
                disabled={!isPro}
                style={{
                  width: '100%',
                  background: 'rgba(0,0,0,0.3)',
                  border: '1px solid rgba(255,255,255,0.1)',
                  borderRadius: '8px',
                  padding: '0.5rem',
                  color: isPro ? 'white' : 'var(--text-muted)',
                  fontSize: '0.85rem',
                  outline: 'none',
                  opacity: isPro ? 1 : 0.5,
                }}
              />
            </div>
          </div>

          {/* Preview */}
          {selectedGames.length > 0 && (
            <div
              style={{
                background: 'rgba(255,255,255,0.02)',
                border: '1px solid rgba(255,255,255,0.05)',
                borderRadius: '10px',
                padding: '0.75rem',
                fontSize: '0.75rem',
                color: 'var(--text-muted)',
              }}
            >
              {(() => {
                const gp = getSimpleBetPrice(activeLottery);
                const total = gp * selectedGames.length;
                const cotas = parseInt(cotasTotal) || 1;
                const taxa = isPro ? parseFloat(taxaPct) || 0 : 0;
                const totalComTaxa = total * (1 + taxa / 100);
                return (
                  <>
                    <div
                      style={{
                        display: 'flex',
                        justifyContent: 'space-between',
                        marginBottom: '0.25rem',
                      }}
                    >
                      <span>
                        {selectedGames.length} jogos × R$ {gp.toFixed(2)}
                      </span>
                      <strong style={{ color: 'white' }}>
                        Total: R$ {total.toFixed(2).replace('.', ',')}
                      </strong>
                    </div>
                    <div
                      style={{
                        display: 'flex',
                        justifyContent: 'space-between',
                        marginBottom: '0.25rem',
                      }}
                    >
                      <span>
                        {cotas} cotas{taxa > 0 ? ` + ${taxa}% taxa` : ''}
                      </span>
                      <strong style={{ color: '#00f0ff' }}>
                        R$ {(totalComTaxa / cotas).toFixed(2).replace('.', ',')}
                        /cota
                      </strong>
                    </div>
                  </>
                );
              })()}
            </div>
          )}

          <button
            onClick={handleCreate}
            disabled={
              loading || selectedGames.length === 0 || !bolaoTitle.trim()
            }
            className="btn-action"
            style={{
              background: `linear-gradient(90deg, ${config?.color || '#00ff88'}, ${config?.accentColor || '#00e676'})`,
              color: 'black',
              fontWeight: 700,
              padding: '0.75rem',
              opacity:
                loading || selectedGames.length === 0 || !bolaoTitle.trim()
                  ? 0.5
                  : 1,
              cursor:
                loading || selectedGames.length === 0 || !bolaoTitle.trim()
                  ? 'not-allowed'
                  : 'pointer',
            }}
          >
            {loading
              ? 'Criando...'
              : `🎲 Criar Bolão (${selectedGames.length} jogos)`}
          </button>

          {/* Created share card */}
          {createdBolao && (
            <div
              style={{
                background: 'rgba(0,230,118,0.05)',
                border: '1px solid rgba(0,230,118,0.2)',
                borderRadius: '12px',
                padding: '1rem',
                textAlign: 'center',
              }}
            >
              <div style={{ fontSize: '2rem', marginBottom: '0.5rem' }}>🎉</div>
              <div
                style={{
                  fontSize: '0.85rem',
                  fontWeight: 700,
                  color: '#00e676',
                  marginBottom: '0.5rem',
                }}
              >
                Bolão criado!
              </div>
              <div
                style={{
                  fontSize: '0.7rem',
                  color: 'var(--text-muted)',
                  marginBottom: '0.75rem',
                }}
              >
                Código:{' '}
                <strong
                  style={{
                    color: 'white',
                    fontFamily: 'monospace',
                    fontSize: '0.85rem',
                    letterSpacing: '0.1em',
                  }}
                >
                  {createdBolao.shareCode}
                </strong>
              </div>
              <div style={{ display: 'flex', gap: '0.5rem' }}>
                <button
                  onClick={() => {
                    navigator.clipboard.writeText(createdBolao.shareCode);
                    setFeedback('✓ Código copiado!');
                  }}
                  style={{
                    flex: 1,
                    padding: '0.5rem',
                    background: 'rgba(255,255,255,0.05)',
                    border: '1px solid rgba(255,255,255,0.1)',
                    borderRadius: '8px',
                    color: 'white',
                    fontSize: '0.7rem',
                    fontWeight: 600,
                    cursor: 'pointer',
                  }}
                >
                  📋 Copiar Código
                </button>
                <button
                  onClick={() => {
                    const myBolao = myBoloes.find(
                      (b) => b.id === createdBolao.id
                    );
                    if (myBolao) handleShareWhatsApp(myBolao);
                  }}
                  style={{
                    flex: 1,
                    padding: '0.5rem',
                    background: '#25D366',
                    border: 'none',
                    borderRadius: '8px',
                    color: 'white',
                    fontSize: '0.7rem',
                    fontWeight: 700,
                    cursor: 'pointer',
                  }}
                >
                  📱 WhatsApp
                </button>
              </div>
            </div>
          )}
        </div>
      )}

      {/* MY BOLÕES */}
      {subView === 'my' && (
        <div
          style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}
        >
          {myBoloes.length === 0 && joinedBoloes.length === 0 ? (
            <p
              style={{
                fontSize: '0.8rem',
                color: 'var(--text-muted)',
                textAlign: 'center',
                padding: '2rem 0',
              }}
            >
              Nenhum bolão criado ou participando ainda.
            </p>
          ) : (
            <>
              {myBoloes.map((bolao) => {
                const bConfig =
                  LOTTERY_CONFIGS[
                    bolao.lottery as keyof typeof LOTTERY_CONFIGS
                  ];
                const cotaValue = bolao.total_cost / bolao.cotas_total;
                return (
                  <div
                    key={bolao.id}
                    style={{
                      padding: '0.75rem',
                      borderRadius: '10px',
                      background: 'rgba(255,255,255,0.02)',
                      border: '1px solid rgba(255,255,255,0.06)',
                    }}
                  >
                    <div
                      style={{
                        display: 'flex',
                        justifyContent: 'space-between',
                        alignItems: 'flex-start',
                        marginBottom: '0.5rem',
                      }}
                    >
                      <div>
                        <div
                          style={{
                            fontSize: '0.85rem',
                            fontWeight: 700,
                            color: 'white',
                          }}
                        >
                          {bolao.title}
                        </div>
                        <div
                          style={{
                            fontSize: '0.65rem',
                            color: 'var(--text-muted)',
                          }}
                        >
                          {bConfig?.name || bolao.lottery} ·{' '}
                          {bolao.games.length} jogos · Criado{' '}
                          {new Date(bolao.created_at).toLocaleDateString(
                            'pt-BR'
                          )}
                        </div>
                      </div>
                      <span
                        style={{
                          fontSize: '0.6rem',
                          padding: '0.15rem 0.4rem',
                          borderRadius: '4px',
                          background:
                            bolao.status === 'active'
                              ? 'rgba(0,230,118,0.15)'
                              : 'rgba(255,255,255,0.05)',
                          color:
                            bolao.status === 'active'
                              ? '#00e676'
                              : 'var(--text-muted)',
                          fontWeight: 600,
                        }}
                      >
                        {bolao.status === 'active' ? 'Ativo' : 'Encerrado'}
                      </span>
                    </div>

                    {/* Games preview */}
                    <div
                      style={{
                        display: 'flex',
                        gap: '0.2rem',
                        flexWrap: 'wrap',
                        marginBottom: '0.5rem',
                      }}
                    >
                      {bolao.games.slice(0, 2).map((game, i) => (
                        <div key={i} style={{ display: 'flex', gap: '0.1rem' }}>
                          {game.slice(0, 6).map((n, ni) => (
                            <span
                              key={ni}
                              style={{
                                width: '20px',
                                height: '20px',
                                borderRadius: '50%',
                                fontSize: '0.55rem',
                                fontWeight: 700,
                                background: `${bConfig?.color || '#00ff88'}22`,
                                border: `1px solid ${bConfig?.color || '#00ff88'}`,
                                color: 'white',
                                display: 'flex',
                                alignItems: 'center',
                                justifyContent: 'center',
                              }}
                            >
                              {String(n).padStart(2, '0')}
                            </span>
                          ))}
                        </div>
                      ))}
                      {bolao.games.length > 2 && (
                        <span
                          style={{
                            fontSize: '0.6rem',
                            color: 'var(--text-muted)',
                            alignSelf: 'center',
                          }}
                        >
                          +{bolao.games.length - 2}
                        </span>
                      )}
                    </div>

                    {/* Stats */}
                    <div
                      style={{
                        display: 'flex',
                        gap: '0.75rem',
                        fontSize: '0.7rem',
                        color: 'var(--text-muted)',
                        marginBottom: '0.5rem',
                      }}
                    >
                      <span>
                        💰 R$ {bolao.total_cost.toFixed(2).replace('.', ',')}
                      </span>
                      <span>
                        👥 {bolao.cotas_taken}/{bolao.cotas_total} cotas
                      </span>
                      <span>
                        💵 R$ {cotaValue.toFixed(2).replace('.', ',')}/cota
                      </span>
                    </div>

                    {/* Progress bar */}
                    <div
                      style={{
                        height: '4px',
                        background: 'rgba(255,255,255,0.1)',
                        borderRadius: '2px',
                        overflow: 'hidden',
                        marginBottom: '0.5rem',
                      }}
                    >
                      <div
                        style={{
                          width: `${(bolao.cotas_taken / bolao.cotas_total) * 100}%`,
                          height: '100%',
                          background: `linear-gradient(90deg, ${bConfig?.color || '#00ff88'}, ${bConfig?.accentColor || '#00e676'})`,
                          borderRadius: '2px',
                          transition: 'width 0.3s',
                        }}
                      />
                    </div>

                    {/* Share code */}
                    <div
                      style={{
                        display: 'flex',
                        alignItems: 'center',
                        gap: '0.5rem',
                        background: 'rgba(0,0,0,0.2)',
                        padding: '0.4rem 0.6rem',
                        borderRadius: '6px',
                        marginBottom: '0.5rem',
                      }}
                    >
                      <span
                        style={{
                          fontSize: '0.6rem',
                          color: 'var(--text-muted)',
                        }}
                      >
                        Código:
                      </span>
                      <code
                        style={{
                          flex: 1,
                          fontSize: '0.8rem',
                          color: 'white',
                          fontFamily: 'monospace',
                          letterSpacing: '0.1em',
                        }}
                      >
                        {bolao.share_code}
                      </code>
                      <button
                        onClick={() => {
                          navigator.clipboard.writeText(bolao.share_code);
                        }}
                        style={{
                          background: 'none',
                          border: 'none',
                          color: 'var(--accent-color)',
                          fontSize: '0.7rem',
                          cursor: 'pointer',
                        }}
                      >
                        📋
                      </button>
                    </div>

                    {/* Actions */}
                    <div style={{ display: 'flex', gap: '0.4rem' }}>
                      <button
                        onClick={() => handleCopyMessage(bolao)}
                        style={{
                          flex: 1,
                          padding: '0.4rem',
                          background: 'rgba(255,255,255,0.05)',
                          border: '1px solid rgba(255,255,255,0.1)',
                          borderRadius: '6px',
                          color: 'white',
                          fontSize: '0.65rem',
                          fontWeight: 600,
                          cursor: 'pointer',
                        }}
                      >
                        📋 Copiar
                      </button>
                      <button
                        onClick={() => handleShareWhatsApp(bolao)}
                        style={{
                          flex: 1,
                          padding: '0.4rem',
                          background: '#25D366',
                          border: 'none',
                          borderRadius: '6px',
                          color: 'white',
                          fontSize: '0.65rem',
                          fontWeight: 700,
                          cursor: 'pointer',
                        }}
                      >
                        📱 WhatsApp
                      </button>
                      <button
                        onClick={() => handleDelete(bolao.id)}
                        style={{
                          padding: '0.4rem 0.6rem',
                          background: 'rgba(255,68,102,0.1)',
                          border: '1px solid rgba(255,68,102,0.2)',
                          borderRadius: '6px',
                          color: '#ff4466',
                          fontSize: '0.65rem',
                          cursor: 'pointer',
                        }}
                      >
                        🗑️
                      </button>
                    </div>
                  </div>
                );
              })}

              {joinedBoloes.length > 0 && (
                <>
                  <div
                    style={{
                      fontSize: '0.7rem',
                      color: 'var(--text-muted)',
                      fontWeight: 700,
                      textTransform: 'uppercase',
                      marginTop: '0.5rem',
                    }}
                  >
                    Participando
                  </div>
                  {joinedBoloes.map((bolao) => {
                    const bConfig =
                      LOTTERY_CONFIGS[
                        bolao.lottery as keyof typeof LOTTERY_CONFIGS
                      ];
                    return (
                      <div
                        key={bolao.id}
                        style={{
                          padding: '0.6rem',
                          borderRadius: '8px',
                          background: 'rgba(255,214,0,0.03)',
                          border: '1px solid rgba(255,214,0,0.15)',
                        }}
                      >
                        <div
                          style={{
                            fontSize: '0.8rem',
                            fontWeight: 600,
                            color: 'white',
                          }}
                        >
                          {bolao.title}
                        </div>
                        <div style={{ fontSize: '0.65rem', color: '#ffd600' }}>
                          Cota #{bolao.cota_num} ·{' '}
                          {bConfig?.name || bolao.lottery} · {bolao.cotas_taken}
                          /{bolao.cotas_total}
                        </div>
                      </div>
                    );
                  })}
                </>
              )}
            </>
          )}
        </div>
      )}

      {/* JOIN VIEW */}
      {subView === 'join' && (
        <div
          style={{
            display: 'flex',
            flexDirection: 'column',
            gap: '1rem',
            alignItems: 'center',
          }}
        >
          <div style={{ fontSize: '2.5rem' }}>🔗</div>
          <p
            style={{
              fontSize: '0.8rem',
              color: 'var(--text-muted)',
              textAlign: 'center',
            }}
          >
            Digite o código de um bolão para entrar como participante.
          </p>
          <input
            type="text"
            value={joinCode}
            onChange={(e) => setJoinCode(e.target.value.toUpperCase())}
            placeholder="Ex: k8f2m9x1"
            maxLength={20}
            style={{
              width: '100%',
              maxWidth: '300px',
              background: 'rgba(0,0,0,0.3)',
              border: '1px solid rgba(255,255,255,0.15)',
              borderRadius: '10px',
              padding: '0.75rem',
              color: 'white',
              fontSize: '1.1rem',
              fontFamily: 'monospace',
              textAlign: 'center',
              letterSpacing: '0.15em',
              outline: 'none',
            }}
            onKeyDown={(e) => e.key === 'Enter' && handleJoin()}
          />
          <button
            onClick={handleJoin}
            disabled={loading || !joinCode.trim()}
            style={{
              padding: '0.7rem 2rem',
              borderRadius: '10px',
              border: 'none',
              background: joinCode.trim()
                ? `linear-gradient(90deg, ${config?.color || '#00ff88'}, ${config?.accentColor || '#00e676'})`
                : 'rgba(255,255,255,0.05)',
              color: joinCode.trim() ? 'black' : 'var(--text-muted)',
              fontSize: '0.85rem',
              fontWeight: 700,
              cursor: joinCode.trim() ? 'pointer' : 'not-allowed',
              opacity: loading ? 0.5 : 1,
            }}
          >
            {loading ? 'Entrando...' : '🎲 Entrar no Bolão'}
          </button>
        </div>
      )}
    </div>
  );
}
